# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift-今日头条02-项目搭建' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift-今日头条02-项目搭建

end
